### ISSUE TITLE
클리앙 로그인 관련 내용입니다.

### ISSUE THREAD

**Issue by mileu32** [liza183/clienBBS#1]
https://www.clien.net/service/board/lecture/11413364
이런 글을 남기고 클량을 탈퇴하여 현재 클량에 댓글을 달 수 없어 깃허브에 남깁니다.

https://github.com/mileu32/ClienRemover
참조하신다면 도움이 될 듯 합니다. 해당 레포에도 설명은 되어있으나, 설명드리자면..

로그인은 https://beomi.github.io/2017/01/20/HowToMakeWebCrawler-With-Login/ 를 참조하시면 쉽게 가능하실 것 같습니다.

제가 분석한 api는 3가지 입니다.
1. 글삭제 
https://www.clien.net/service/board/park/11439917 를 삭제하시고 싶으시면,
https://www.clien.net/service/api/board/park/delete 에
{'boardSn':  11439917} 를 post 하시면 됩니다.

2. 댓글 삭제
<img width="1427" alt="default" src="https://user-images.githubusercontent.com/13388715/32979997-4bb41ec0-cca2-11e7-9a6f-f6f91e0dc9c3.PNG">
https://www.clien.net/service/api/board/park/11439917/comment/delete/84284993 하시면 됩니다.

3. 댓글 리스트(json)
https://www.clien.net/service/api/board/park/11439917/comment?param=%7B%22order%22%3A%22date%22%2C%22po%22%3A0%2C%22ps%22%3A999999%7D
이미 구현하셔서 방법은 아실 것이라고 생각합니다. 그래도 혹시나 싶어서 다시 남겨 봅니다.

모든 요청은 csrf라는 것을 포함해야 정상적으로 동작합니다. 자세한 동작은https://github.com/mileu32/ClienRemover/blob/master/ClienRemover.py 를 참조해주세요. 제가 현직이 아니라.. 잘못된 설명 등이 포함될 수 있는 점 죄송합니다.

재미있는 프로그램을 개발해주셔서 감사합니다.

**Comment by liza183** [comment]
와 대단히 감사합니다! 그런데 ... 로긴이 되었는지 안되었는지 확인하는 status_code 200이 아이디 암호가 잘못되어도 200으로 나오는데 혹시 왜그런지 아시는지요? 로긴이 된것을 어떻게 정확히 확인할수 있나요

**Comment by mileu32** [comment]
확인이 늦었네요ㅠㅠ
200 코드는 http 응답 코드여서 정상적으로 페이지가 호출되었으면 응답되는 거라.. 로그인 실패하여도 200 이 리턴됩니다. 
참조 : https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

![image](https://user-images.githubusercontent.com/13388715/33200674-f2ebb9a6-d138-11e7-9ee1-e323b7ddc99b.png)
로그인을 확인하시려면 로그인 될 경우 나타나는 사용자 창을 html 파싱하셔서 특정 조건(예를 들어 로그인 입력 폼이 없다던가..)을 기준으로 확인하시면 될 것 같습니다.
제가 현재 클리앙 계정이 없어서 정확히 확인할 수 없는 점 죄송합니다.

**Comment by liza183** [comment]
대단히 감사합니다.
현재 댓글 달기까지는 어떻게 했고
글쓰기 작업중인데 참 ... 생각처럼 쉽지않네요 ㅠ

**Comment by junseunge** [comment]
지금 뒤늦게 이 글 보고 시도중인 중생이라고 합니다 ㅠ

클리앙이 몇일전에 개편이 됐었는데 (큰 개편은 아니고, 사이트 UI의 변화 같은-) 그것 때문인지 작동이 안하네요 저 기능이.. 파일 실행하면 그냥 강제종료 되어버립니다. 

어떻게 못할까요? ㅠㅠ

**Comment by liza183** [comment]
음~ 개편때문은 아닐거에요 개편 이후 업데이트를 해서요~ 
설명대로 pip install clienBBS로 설치해보세요~

**Comment by junseunge** [comment]
제가 스레드를 잘못 찾아왔나 보네요 퓨  ㅠㅠ

제가 말한건 그 클리앙 글 전체삭제기가 안된다는 뜻이였습니다 ㅠㅠ
